import { Router } from 'express';
import stockRequestRoutes from './stock-request/stock-request.routes';
import reportsRoutes from './reports/reports.routes';
import menuRoutes from './menu/menu.routes';
import orderRoutes from './order/order.routes';
import inventoryCategoryRoutes from './inventory-category/inventory-category.routes';
import inventoryUnitRoutes from './inventory-unit/inventory-unit.routes';
import inventoryItemRoutes from './inventory-item/inventory-item.routes';
import supplierRoutes from './supplier/supplier.routes';
import purchaseOrderRoutes from './purchase-order/purchase-order.routes';
import goodsReceivingRoutes from './goods-receiving/goods-receiving.routes';
import batchRoutes from './batch/batch.routes';
import departmentInventoryRoutes from './department-inventory/department-inventory.routes';
import settingRoutes from './setting/setting.routes';
import adjustmentReasonRoutes from './adjustment-reason/adjustment-reason.routes';
import inventoryAdjustmentRoutes from './inventory-adjustment/inventory-adjustment.routes';

import expenseRoutes from './expense/expense.routes';
import expenseCategoryRoutes from './expense/expense-category.routes';

import tableRoutes from './table/table.routes';
import reservationRoutes from './reservation/reservation.routes';
import paymentRoutes from './payment/payment.routes';
import staffRoutes from './staff/staff.routes';
import dissatisfactionRoutes from './dissatisfaction/dissatisfaction.routes';
import barReturnRoutes from './bar-return/bar-return.routes';
import departmentRoutes from './department/department.routes';
import staffRoleRoutes from './staff-role/staff-role.routes';
import permissionRoutes from './permission/permission.routes';
import userGroupRoutes from './user-group/user-group.routes';
import userRoutes from './user/user.routes';
import accountingRoutes from './accounting/accounting.routes';

const router = Router();

router.use('/menu', menuRoutes);
router.use('/order', orderRoutes);
router.use('/inventory-category', inventoryCategoryRoutes);
router.use('/inventory-unit', inventoryUnitRoutes);
router.use('/inventory-item', inventoryItemRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/purchase-orders', purchaseOrderRoutes);
router.use('/goods-receiving', goodsReceivingRoutes);
router.use('/batches', batchRoutes);
router.use('/department-inventory', departmentInventoryRoutes);
router.use('/stock-request', stockRequestRoutes);
router.use('/expenses', expenseRoutes);
router.use('/expense-categories', expenseCategoryRoutes);
router.use('/tables', tableRoutes);
router.use('/reservations', reservationRoutes);
router.use('/payments', paymentRoutes);
router.use('/settings', settingRoutes);
router.use('/adjustment-reasons', adjustmentReasonRoutes);
router.use('/inventory-adjustments', inventoryAdjustmentRoutes);
router.use('/staff', staffRoutes);
router.use('/dissatisfactions', dissatisfactionRoutes);
router.use('/bar-returns', barReturnRoutes);
router.use('/departments', departmentRoutes);
router.use('/staff-roles', staffRoleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/user-groups', userGroupRoutes);
router.use('/users', userRoutes);
router.use('/accounting', accountingRoutes);
router.use('/reports', reportsRoutes);

export default router;
